
server.port=8082

spring.application.name=ActivityService

#for MongoDBmongodb://127.0.0.1:27017/dutyfixit_db
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/ActivityService
spring.data.mongodb.database=ActivityService
#spring.data.mongodb.username=nagarajpriyan2004_db_user
#spring.data.mongodb.password=mani


